---
title: "supplement"
author: '@yatingxie'
date: "2021/5/24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r df1-2, echo=TRUE}
library(ggplot2)

# Define UI for application that draws a histogram
ui <- fluidPage(
  
  # Application title
   titlePanel("City development index and The time length of training for the new job"),
   
   # Sidebar with a slider input for number of bins 
   sidebarLayout(
      sidebarPanel(
                 radioButtons("display_var",
                      "Which variable to display",
                      choices = c("City development index" = "city_development_index",
                                  "The time length of training for the new job" = "training_hours"),
                      selected = "training_hours"
         ),
         sliderInput("bins",
                     "Number of bins:",
                     min = 1,
                     max = 300,
                     value = 50)
      ),
      
      # Show a plot of the generated distribution
      mainPanel(
         plotOutput("distPlot")
      )
   )
)

# Define server logic required to draw a histogram
server <- function(input, output) {
   
   output$distPlot <- renderPlot({
      # set x-axis label depending on the value of display_var
      if (input$display_var == "city_development_index") {
        xlabel <- "City development index"
      } else if (input$display_var == "training_hours") {
        xlabel <- "The time length of training for the new job"
      }

      # create plot
      ggplot(df1, aes(df1[[input$display_var]])) +
        geom_histogram(bins = input$bins,
                       fill = "steelblue3",
                       colour = "grey30") +
        xlab(xlabel) +
        theme_minimal()
    })
}

```


